NumPy (video)
    Lists
        Powerful
        Collection of values
        Hold different types
        Change, add, remove
        When analyzing data, mathematical operations need to be carried out over entire collections of values at a very fast speed
    NumPy
        Numeric Python
        Arrays
            An alternative to Python Lists
            Can do quick calculations over entire arrays
            Contain only one type, so if different types are put in they will all convert to strings
            A new kind of Python type with its own methods
        Subsetting
            Can be found through indexing (like Python lists) or booleans
    Comparison
        Python doesn't know how to do calculations with regular lists
        NumPy knows how to work with arrays like a list of single values


In [6]:
#NumPy (video)

#create lists
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

#error when finding the BMI
#weight / height ** 2 #Python doesn't know how to do calculations on lists

#import numpy
import numpy as np
#create a numpy array with the input being a regular Python list (object so method)
np_height = np.array(height)
np_weight = np.array(weight)

#calculations were performed element wise with numpy rather than getting an error
bmi = np_weight / np_height ** 2
print(bmi)

#NumPy array string conversion of different data types
print(np.array([1.0, "is", True]))

#NumPy arrays act differently when combined compared to Python lists
#Python lists are put together
pythonCombined = height + weight
print(pythonCombined)
#NumPy arrays add the values within together
numpyCombined = np_height + np_weight
print(numpyCombined)

#Subsetting
#indexing with square brackets (like Python lists)
print(bmi[1])
#boolean true and false
print(bmi > 23)
#subset boolean array with square brackets
bmi[bmi > 23]

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]
['1.0' 'is' 'True']
[1.73, 1.68, 1.71, 1.89, 1.79, 65.4, 59.2, 63.6, 88.4, 68.7]
[67.13 60.88 65.31 90.29 70.49]
20.97505668934241
[False False False  True False]


array([24.7473475])

First NumPy Array (exercise)

In [ ]:
#instructions
    #Import the numpy package as np, so that you can refer to numpy with np.
    #Use np.array() to create a numpy array from baseball. Name this array np_baseball.
    #Print out the type of np_baseball to check that you got it right.

#Import the numpy package as np
import numpy as np

baseball = [180, 215, 210, 210, 188, 176, 209, 200]

#Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

#Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


Baseball Players' Height (exercise)

In [11]:
#instructions
    #Create a numpy array from height_in. Name this new array np_height_in.
    #Print np_height_in.
    #Multiply np_height_in with 0.0254 to convert all height measurements from inches to meters. Store the new values in a new array, np_height_m.
    #Print out np_height_m and check if the output makes sense.

#Import numpy
import numpy as np

#create a list manually for height_in (already found in DataCamp, but not downloaded in particular environment)
height_in = [74, 74, 72, 75, 75, 73]

#Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

#Print out np_height_in
print(np_height_in)

#Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

#Print np_height_m
print(np_height_m)

[74 74 72 75 75 73]
[1.8796 1.8796 1.8288 1.905  1.905  1.8542]


NumPy Side Effects (exercise)
    NumPy is great for vector arithmetic, although some functionalities have changed compared to Python lists
        NumPy arrays cannot contain elements of different types and will automatically convert them to a common type
        NumPy arrays see typical arithmetic operators, such as +, -, *, and / differently than Python lists

In [14]:
import numpy as np

#instructions
    #select an answer that matches the line of code below
        #np.array([True, 1, 2, 3, 4, False])
        #np.array([4, 3, 0]) + np.array([0, 2, 2])
        #np.array([1, 1, 2]) + np.array([3, 4, -1])
        #np.array([0, 1, 2, 3, 4, 5])

#when integers and booleans are together, everything is changed to an integer, with True as 1 and False as 0
print(np.array([True, 1, 2]) + np.array([3, 4, False]))

#answer 1
print(np.array([True, 1, 2, 3, 4, False]))

#answer 2
print(np.array([4, 3, 0]) + np.array([0, 2, 2]))

#answer 3
print(np.array([1, 1, 2]) + np.array([3, 4, -1]))

#answer 4
print(np.array([0, 1, 2, 3, 4, 5]))

[4 5 2]
[1 1 2 3 4 0]
[4 5 2]
[4 5 1]
[0 1 2 3 4 5]


Subsetting NumPy Arrays (exercise)
    Subsetting (using square bracket notation) works exactly the same with both lists and arrays

In [15]:
#instructions
    #Subset np_weight_lb by printing out the element at index 2.
    #Print out a sub-array of np_height_in that contains the elements at index 5 up to and including index 10.

import numpy as np

#manually create lists, since MLB data is already loaded into DataCamp
weight_lb = [150, 175, 200, 225, 250, 150, 175, 200, 225, 250]
height_in = [75, 80, 85, 90, 95, 75, 80, 85, 90, 95]

np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

#Print out the weight at index 3
print(np_weight_lb[3])

#Print out sub-array of np_height_in: index 5 up to and including index 10
print(np_height_in[5:11])

225
[75 80 85 90 95]


2D NumPy Arrays (video)
    2D NumPy Array
        Each subset in the list corresponds to a row in the two dimensional NumPy array
        shape is an attribute of a NumPy array that can give more info about what the data structure looks like
            Syntax looks kind of like calling a method, but they are not the same, as methods have round brackets after them
        Can only contain a single type, so the NumPy can be homogenous
        Improved lists of lists, performing advanced calculations, subsetting, etc.
        Can perform element wise calculations

In [22]:
#2D NumPy Arrays (video)

import numpy as np

#create 2D NumPy array of the heights and weights of family members
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                    [65.4, 59.2, 63.6, 88.4, 68.7]])
print(np_2d)

#shape of the NumPy array
print(np_2d.shape)

#subsetting
#select a specific value in the array by first choosing the row and then the column
print(np_2d[0][2])
#can be done by using single square brackets and a comma
print(np_2d[0, 2])
#find specific sections within the 2D NumPy array
#select height and weight of second and third family members
print(np_2d[:, 1:3]) #both height/weight rows and then indices 1 through 3 for the 2nd and 3rd columns
#weight of all family members
print(np_2d[1, :]) #only weight row but all family members in every column

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]
(2, 5)
1.71
1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]
[65.4 59.2 63.6 88.4 68.7]


First 2D NumPy Array (exercise)

In [ ]:
#instructions
    #Use np.array() to create a 2D numpy array from baseball. Name it np_baseball.
    #Print out the type of np_baseball.
    #Print out the shape attribute of np_baseball. Use np_baseball.shape.

import numpy as np

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

#Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

#Print out the type of np_baseball
print(type(np_baseball))

#Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


Subsetting 2D NumPy Arrays (exercise)
    When a 2D NumPy Array has a fixed structure (rows/columsn have fixed number of values), complicated ways of subsetting become easy
    Indexes before the comma refer to rows, while those after the comma refer to columns
    : is for full inclusion when slicing

In [ ]:
#instructions
    #Print out the 2nd row of np_baseball.
    #Make a new variable, np_weight_lb, containing the entire second column of np_baseball.
    #Select the height (first column) of the 3rd baseball player in np_baseball and print it out.

import numpy as np

#create a list, with first column being height and second being weight
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

#Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

#Print out the 2nd row of np_baseball
print(np_baseball[1, :])

#Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:, 1]
print(np_weight_lb)

#Print out height of 3rd player
print(np_baseball[2, 0])

[215.  102.7]
[ 78.4 102.7  98.5  75.2]
210.0


2D Arithmetic (exercise)
    2D NumPy arrays can perform calculations element by element

In [3]:
#instructions
    #You managed to get hold of the changes in height, weight and age of all baseball players. It is available as a 2D numpy array, updated. Add np_baseball and updated and print out the result.
    #You want to convert the units of height and weight to metric (meters and kilograms, respectively). As a first step, create a numpy array with three values: 0.0254, 0.453592 and 1. Name this array conversion.
    #Multiply np_baseball with conversion and print out the result.

import numpy as np

#create a list of height (in), weight (lbs) and age (yrs)
baseball = [[74., 180., 25.99],
            [74., 215., 31.69],
            [75., 190., 27.78],
            [73., 195., 28.01]]

np_baseball = np.array(baseball)

#Print out addition of np_baseball and updated
#create a list with updated changes
updated_list =   [[1.2303559, -11.16224898, 1.],
            [1.02614252, 16.09732300, 1.],
            [1.1544228, 5.08167641, 1.],
            [1.09349925, 4.23890778, 1.]]
#change to NumPy array
updated = np.array(updated_list)
#print combined list with changes
print(np_baseball+ updated)

#Create numpy array: conversion
conversion_list = [[0.0254, 0.453592, 1]]
#change to NumPy array
conversion = np.array(conversion_list)

#Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 75.2303559  168.83775102  26.99      ]
 [ 75.02614252 231.097323    32.69      ]
 [ 76.1544228  195.08167641  28.78      ]
 [ 74.09349925 199.23890778  29.01      ]]
[[ 1.8796  81.64656 25.99   ]
 [ 1.8796  97.52228 31.69   ]
 [ 1.905   86.18248 27.78   ]
 [ 1.8542  88.45044 28.01   ]]


NumPy Basic Statistics (video)
    Data Analysis
        Get to know data
        Little data is simple to look out, but what about a large amount of data
    NumPy
        mean function finds average
        median function finds the middle value(s) when sorted
        corrrcoef function to check if there is correlation between values
        std function for standard deviation
        sum and sort functions are included, which also exist in Python
            NumPy's enforcement of a single data type in an array drastically speeds up calculations compared to Python
    Generate Data
        random.normal function to create random distributions
            Attributes include distribution mean, distribution standard deviation, and number of samples
        round for rounding decimal places
        column_stack function to paste together as two columns

In [ ]:
#Large Data (video)
import numpy as np

#city-wide survey data (pretend to ahve 5000 lines)
#create a list
np_city_list = ([1.64, 71.78],
                [1.37, 63.35],
                [2.04, 74.85],
                [2.04, 68.72],
                [2.01, 73.57])
#change to NumPy array
np_city = np.array(np_city_list)

#mean height of city
print(np.mean(np_city[:, 0]))

#median height of city
print(np.median(np_city[:, 0]))

#correlation check between city heights and weights
print(np.corrcoef(np_city[:, 0], np_city[:,1]))

#standard deviation
print(np.std(np_city[:,0]))

#generate large amount of data
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

large_np_city = np.column_stack((height, weight))
print(large_np_city)

1.8199999999999998
2.01
[[1.         0.74289454]
 [0.74289454 1.        ]]
0.2712194683277732
[[ 1.35 38.73]
 [ 1.83 61.91]
 [ 1.53 59.91]
 ...
 [ 1.75 56.38]
 [ 1.71 71.67]
 [ 1.56 73.26]]


Average versus Median (exercise)

In [19]:
#instructions
    #Create numpy array np_height_in that is equal to first column of np_baseball.
    #Print out the mean of np_height_in.
    #Print out the median of np_height_in.

import numpy as np

#create a mock NumPy array of baseball data with  3 columns (height, weight, age) and 1015 rows
height = np.round(np.random.normal(73, 0.20, 1050), 2)
weight = np.round(np.random.normal(195, 15, 1050), 2)
age = np.round(np.random.normal(30, 5, 1050), 2)

np_baseball = np.column_stack((height, weight, age))
print(np_baseball)

#Create np_height_in from np_baseball
np_height_in = np_baseball[:, 0]
print(np_height_in)

#Print out the mean of np_height_in
print(np.mean(np_height_in))

#Print out the median of np_height_in
print(np.median(np_height_in))

[[ 72.73 191.48  23.36]
 [ 72.77 195.63  24.94]
 [ 72.72 178.44  22.44]
 ...
 [ 72.9  212.26  30.13]
 [ 73.06 198.97  32.18]
 [ 73.38 228.73  32.28]]
[72.73 72.77 72.72 ... 72.9  73.06 73.38]
73.00273333333332
73.01


Explore Baseball Data (exercise)

In [21]:
#instructions
    #The code to print out the mean height is already included. Complete the code for the median height.
    #Use np.std() on the first column of np_baseball to calculate stddev.
    #Do big players tend to be heavier? Use np.corrcoef() to store the correlation between the first and second column of np_baseball in corr.

import numpy as np

#create a mock NumPy array of baseball data with  3 columns (height, weight, age) and 1015 rows
height = np.round(np.random.normal(73, 0.20, 1050), 2)
weight = np.round(np.random.normal(195, 15, 1050), 2)
age = np.round(np.random.normal(30, 5, 1050), 2)

np_baseball = np.column_stack((height, weight, age))
print(np_baseball)

avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height
med = np.median(np_baseball[:, 0])
print("Median: " + str(med))

# Print out the standard deviation on height
stddev = np.std(np_baseball[:, 0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column
corr = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])
print("Correlation: " + str(corr))

[[ 73.02 189.84  17.13]
 [ 73.09 167.48  28.21]
 [ 73.27 224.28  26.1 ]
 ...
 [ 73.13 199.16  28.22]
 [ 72.6  199.72  32.27]
 [ 73.07 191.04  34.99]]
Average: 72.99948571428571
Median: 73.0
Standard Deviation: 0.20408290165591852
Correlation: [[1.         0.03427527]
 [0.03427527 1.        ]]
