Functions (video)
    A piece of reusable code that solves a particular task
    Call function instead of writing code
    Can be assigned and called through variables
    When doing a standard task, a function for it probably exists
    Internet is a good friend
    Arguments can either be required or optional (usually in [] from documentation)

In [ ]:
#functions (example)

#create a list
fam = [1.73, 1.68, 1.71, 1.89]

#max function to find the largest number in the list
#finds the tallest family member height
tallest = max(fam)
print(tallest)

#round function to round number and the precision at which should be rounded to (decimal place)
#rounds 1.68 to 1 decimal place
rounded = round(1.68, 1)
print(rounded)
#defaults if decimal place is omitted, as ndigits is an optional argument
omittedRound = round(1.68)
print(omittedRound)

#help function to open up documentation on different functions
help(round)

1.89
1.7
2
Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



Familiar Functions (exercise)
    Python offers built-in functions to make data science easier
        print() (prints out results) and type() (finds data type) have already been used previously
        str(), int(), bool(), and float() to switch between data types
        https://docs.python.org/3/library/functions.html to learn about all of them

In [ ]:
#instructions
    #Use print() in combination with type() to print out the type of var1.
    #Use len() to get the length of the list var1. Wrap it in a print() call to directly print it out.
    #Use int() to convert var2 to an integer. Store the output as out2.

#Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

#Print out type of var1 (currently a list)
print(type(var1))

#Print out length of var1
print(len(var1))

#Convert var2 to an integer: out2
out2 = int(var2)
print(out2)

<class 'list'>
4
1


Help! (exercise)
    the help() function can be utilized to ask for info about a function

In [ ]:
#instructions
    #Possible answers
        #pow() takes three arguments: base, exp, and mod. Without mod, the function will return an error.
        #pow() takes three required arguments: base, exp, and None.
        #pow() requires base and exp arguments; mod is optional.
        #pow() takes two arguments: exp and mod. Missing exp results in an error.

help(pow)
#https://docs.python.org/3/library/functions.html#pow if it doesn't make sense
#pow() requires base and exp arguments; mod is optional is the correct answer

Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



Multiple Arguments (exercise)

In [14]:
#instructions
    #Use + to merge the contents of first and second into a new list: full.
    #Call sorted() and on full and specify the reverse argument to be True. Save the sorted list as full_sorted.
    #Finish off by printing out full_sorted.

#figure out what the sort function does with help
help(sorted)
#https://docs.python.org/3/library/functions.html#sorted if it doesn't make sense

#Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

#Paste together first and second: full
full = first + second

#Sort full in descending order: full_sorted
#three arguments: iterable (put in list - required), key (specifies a function used to extract key comparison with default comparing directly - optional), and reverse (descending instead of ascending order - optional)
full_sorted = sorted(full, key=None, reverse=True)

#Print out full_sorted
print(full_sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.

[20.0, 18.0, 11.25, 10.75, 9.5]


Methods (video)
    Built-in Functions
        Maximum in list: max()
        Length of list/string: len()
        Getting an index in a list or reversing a list is not built-in
    Back2Basics
        Each value/data structure are Python objects with specific types (str, float, list, etc.)
        Methods: Calls functions that belong to objects
    Methods
        Everything is an object
        Objects have methods associated depending on the type
        Objects of different types can have methods with the same name
            index() method for strings and lists
        Some can change the objects they are called on
            append() method

In [21]:
#methods (video)

#Object str (type) with method examples like capitalize(), replace()
sister = "liz"
print(sister.capitalize())
print(sister.replace("z", "sa"))

#Object float (type) with method examples like bit_length(), conjugate()
height = 1.73

#Object list (type) with method examples like index(), count()
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "data", 1.89]
#a . is used to call the method on fam list
print(fam.index("mom"))
print(fam.count(1.73))

#index method used on both strings and lists
print(sister.index("z")) #string
print(fam.index("mom")) #list

#append method used to change a list object from what it originally was
print(fam.append("me"))
print(fam)

Liz
lisa
4
1
2
4
None
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'data', 1.89, 'me']


String Methods (exercise)

In [ ]:
#instructions
    #Use the .upper() method on place and store the result in place_up. Use the syntax for calling methods that you learned in the previous video.
    #Print out place and place_up. Did both change?
    #Print out the number of o's on the variable place by calling .count() on place and passing the letter 'o' as an input to the method. We're talking about the variable place, not the word "place"!

#help to see what string methods there are and what they can do
help(str)
#https://docs.python.org/3/library/stdtypes.html#string-methods if it doesn't make sense

# string to experiment with: place
place = "poolhouse"

# Use upper() on place
place_up = place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place
print(place.count('o'))

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

List Methods (exercise)
    .index()
        Gets the index of the first element of a list that matches its input
    .count()
        Gets the number of times an element appears in a list

In [ ]:
#instructions
    #Use the .index() method to get the index of the element in areas that is equal to 20.0. Print out this index.
    #Call .count() on areas to find out how many times 9.50 appears in the list. Again, simply print out this number.

#help to see what list methods can be done
help(list)
#https://docs.python.org/3/tutorial/datastructures.html if it doesn't make sense

#Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

#Print out the index of the element 20.0
print(areas.index(20.0))

#Print out how often 9.50 appears in areas
print(areas.count(9.50))

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

List Methods (2) (exercise)
    .append()
        Adds an element to the list it is called on
    .remove()
        Removes the first element of a list that matches input
    .reverse()
        Reverses the order of elements in the list it is called on

In [30]:
#instructions
    #Use .append() twice to add the size of the poolhouse and the garage again: 24.5 and 15.45, respectively. Make sure to add them in this order.
    #Print out areas
    #Use the .reverse() method to reverse the order of the elements in areas.
    #Print out areas once more.

#help for list methods
help(list)
#https://docs.python.org/3/tutorial/datastructures.html if it doesn't make sense

#Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

#Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

#Print out areas
print(areas)

#Reverse the orders of the elements in areas
areas.reverse()

#Print out areas
print(areas)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

Packages (video)
    Functions and methods are powerful
    Adding all functions to the same Python distribution would be a huge code mess
    Packages
        Directory of Python Scripts
        Each script is a module, which specify functions, methods, and new Python tyhpes aimed for solving particular problems
            NumPy, Matplotlib, scikit-learn
    Install Package
        Currently using conda environment with the necessary packages installed (can install more later)
    Import Package
        Use "import BLANK" at the top of code script to properly obtain the package
        A nickname is usually given to packages using "as" so it's easier to call
        Specific parts of a package can be called with "from" at the start
            General imports with nicknames are preferred over specific imports without

In [ ]:
#packages (video)

#import package at the top
#import numpy
#package nickname
#import numpy as np
#call specific part of package
from numpy import array

#package.prefix
#numpy.array([1, 2, 3])
#packagenickname.prefix
#np.array([1, 2, 3])
#part of package
array([1, 2, 3])

array([1, 2, 3])

Import Package (exercise)
    Rather than typing the number for pi, the math package contains that number
    ** is the symbol for an exponentiation
        3**4 is 3 to the power of 4, which will give 81

In [34]:
#Import the math package
import math

#Calculate C
#Circumference = 2"pi"r
C = 2 * 0.43 * math.pi

#Calculate A
#Area = "pi"r^2
A = math.pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))



Circumference: 2.701769682087222
Area: 0.5808804816487527


Selective Import (exercise)

In [35]:
#Import pi function of math package
from math import pi

#Calculate C
C = 2 * 0.43 * pi

#Calculate A
A = pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


Different Ways of Importing (exercise)

In [ ]:
#import scipy #doesn't work bc my_inv isn't defined
#import scipy.linalg #doesn't work bc my_inv isn't defined
#from scipy.linalg import my_inv #doesn't work bc my_inv is a variable, not a part of the package
from scipy.linalg import inv as my_inv #works!

#instructions
    #Suppose you want to use the function inv(), which is in the linalg subpackage of the scipy package. You want to be able to use this function as follows:
my_inv([[1,2], [3,4]])
    #Which import statement will you need in order to run the above code without an error?
        #import scipy
        #import scipy.linalg
        #from scipy.linalg import my_inv
        #from scipy.linalg import inv as my_inv


array([[-2. ,  1. ],
       [ 1.5, -0.5]])